### ISSUE TITLE
Derive image styles from frontend configuration

### ISSUE THREAD

**Issue by pmelab** [amazeeio-solutions/silverback-mono#1073]
The UI packages/frontend code should be able to declare required image styles (e.g. aspect ratio + breakpoints) which automatically become available in Drupal.

Example:

```yml
breakpoints:
- 480
- 768
- 1220
presets:
- name: teaser
  aspect-ratio: 4/3
- name: hero
  aspect-ration: 16/9
```
